api/urls.py
from django.urls import path, include
from rest_framework import routers
from api.views import MedicalDataViewSet, SickUserViewSet, MedicalPractitionerViewSet, UserViewSet

router = routers.DefaultRouter()
router.register("data/medics", MedicalDataViewSet)
router.register("data/user", SickUserViewSet)
router.register("data/medicalpractitioner", MedicalPractitionerViewSet)
router.register("data/users", UserViewSet)

urlpatterns = [
    path("", include(router.urls))
]

data/urls.py
from django.urls import path
from django.views.generic import TemplateView as temp_view
from data.views import StatisticsView, MedicalDataView, DashBoardView

app_name = "data"
urlpatterns = [
    # path("", temp_view.as_view(template_name="records/dashboard.html"), name="dashboard"),
    path("", DashBoardView.as_view(), name="dashboard"),
    path("statistics/", StatisticsView.as_view(), name="statistics"),
    path("medical/", MedicalDataView.as_view(), name="medical-data"),
]

medwebapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView as temp_view
from data.views import DashBoardView as dashboardview


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('rest_framework.urls')),
    path('api/', include('api.urls'),),
    path('accounts/', include('users.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('data/', include('data.urls')),
    path('dashboard/', dashboardview.as_view(), name='dashboard'),
    path('', temp_view.as_view(template_name='index.html'), name='home'),
]

users/urls.py
from django.urls import path
from users.views import SignUpView, MedPractSignUpView, ProfileView

app_name = "users"
urlpatterns = [
    path('profile', ProfileView.as_view(), name='profile'),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('practitioner/signup/', MedPractSignUpView.as_view(), name='practitioner-signup'),
]

templates/includes/navbar.html
{% load static %}
<!-- Navbar -->
  <div class="container px-4">
    <nav class="navbar navbar-top navbar-expand-md navbar-dark" id="navbar-main">
        <div class="container-fluid">
            <!-- Brand -->
            <a class="h4 mb-0 text-white text-uppercase d-none d-lg-inline-block navbar-brand" href="{% url 'home' %}">
                <img class="navbar-brand-img" width="40" height="40" src="{% static 'assets/img/brand/hospital-logo.png' %}" alt="Brand logo"> <span>Medical Web Application</span>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-collapse-main" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="mx-auto d-md-none">
                <img class="navbar-brand-img" width="30" height="30" src="{% static 'assets/img/brand/hospital-logo.png' %}" alt="Brand logo"> <span class="text-white font-weight-bold">Medical Web App</span>
            </div>
            <div class="collapse navbar-collapse" id="navbar-collapse-main">
                <!-- Collapse header -->
                <div class="navbar-collapse-header d-md-none">
                    <div class="row">
                    <div class="col-6 collapse-brand">
                        <a href="{% url 'home' %}">
                        <img src="{% static 'assets/img/brand/hospital-logo.png' %}">
                        <span>Medical Web Application</span>
                        </a>
                    </div>
                    <div class="col-6 collapse-close">
                        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle sidenav">
                        <span></span>
                        <span></span>
                        </button>
                    </div>
                    </div>
                </div>
                <!-- Navbar items -->
                <ul class="navbar-nav ml-auto">
                    {% if not user.is_authenticated %}
                        <li class="nav-item btn btn-sm shadow-none--hover">
                            <a href="{% url 'users:signup' %}" class="nav-link">
                                Sick User Register
                            </a>
                        </li>
                        <li class="nav-item btn btn-sm shadow-none--hover">
                            <a href="{% url 'users:practitioner-signup' %}" class="nav-link">
                                Medical Practitioner Register
                            </a>
                        </li>
                        <li class="nav-item btn btn-sm shadow-none--hover">
                            <a href="{% url 'login' %}" class="nav-link">
                                Login
                            </a>
                        </li>
                    {% else %}
                        <li class="nav-item dropdown">
                            <a class="nav-link pr-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <div class="media align-items-center">
                                <span class="avatar avatar-sm rounded-circle">
                                    <img alt="Image placeholder" src="{% static 'assets/img/theme/team-4-800x800.jpg' %}">
                                </span>
                                <div class="media-body ml-2 d-none d-lg-block">
                                    <span class="mb-0 text-sm  font-weight-bold">Hi {{user.username}}!</span>
                                </div>
                                </div>
                            </a>
                            <div class="dropdown-menu dropdown-menu-arrow dropdown-menu-right">
                                <div class=" dropdown-header noti-title">
                                <h6 class="text-overflow m-0">Welcome!</h6>
                                </div>
                                <a href="{% url 'users:profile' %}" class="dropdown-item">
                                    <i class="ni ni-single-02"></i>
                                    <span>My profile</span>
                                </a>
                                <a href="{% url 'data:dashboard' %}" class="dropdown-item">
                                    <i class="ni ni-ui-04"></i>
                                    <span>Dashboard</span>
                                </a>
                                <div class="dropdown-divider"></div>
                                <a href="{% url 'logout' %}" class="dropdown-item">
                                    <i class="ni ni-user-run"></i>
                                    <span>Logout</span>
                                </a>
                            </div>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
  </div>
        <!-- End Navbar -->
      <!-- <div class="panel-header panel-header-lg">

templates/includes/side_navbar.html
{% load static %}
<nav class="navbar navbar-vertical fixed-left navbar-expand-md navbar-light bg-white" id="sidenav-main">
    <div class="container-fluid">
        <!-- Toggler -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <!-- Brand -->
        <a class="navbar-brand p-3 bold" href="{% url 'home' %}">
            <img src="{% static 'assets/img/brand/hospital-logo.png' %}" class="navbar-brand-img" alt="Brand logo"> <span class="h-100">Medical Web App</span>
        </a>
        <!-- User -->
        <ul class="nav align-items-center d-md-none">
            <li class="nav-item dropdown">
                <a class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <div class="media align-items-center">
                    <span class="avatar avatar-sm rounded-circle">
                        <img alt="Image placeholder" src="{% static 'assets/img/theme/team-1-800x800.jpg' %}">
                    </span>
                </div>
                </a>
                <div class="dropdown-menu dropdown-menu-arrow dropdown-menu-right">
                    <div class=" dropdown-header noti-title">
                        <h6 class="text-overflow m-0">Welcome!</h6>
                    </div>
                    <a href="#" class="dropdown-item">
                        <i class="ni ni-single-02"></i>
                        <span>My profile</span>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="#!" class="dropdown-item">
                        <i class="ni ni-user-run"></i>
                        <span>Logout</span>
                    </a>
                </div>
            </li>
        </ul>
        <!-- Collapse -->
        <div class="collapse navbar-collapse" id="sidenav-collapse-main">
            <!-- Collapse header -->
            <div class="navbar-collapse-header d-md-none">
                <div class="row">
                <div class="col-6 collapse-brand">
                    <a href="{% url 'home' %}">
                    <img src="{% static 'assets/img/brand/doctor-medical-mk-logo.png' %}"> <span class="text-black-50">MWA</span>
                    </a>
                </div>
                <div class="col-6 collapse-close">
                    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle sidenav">
                    <span></span>
                    <span></span>
                    </button>
                </div>
                </div>
            </div>
            <!-- Navigation -->
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class=" nav-link active " href="{% url 'data:dashboard' %}">
                        <i class="ni ni-tv-2 text-primary"></i> Dashboard
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="{% url 'users:profile' %}">
                        <i class="ni ni-single-02 text-yellow"></i> User profile
                    </a>
                </li>
                {% if user.is_staff %}
                    <li class="nav-item">
                        <a class="nav-link " href="{% url 'data:medical-data' %}">
                            <i class="ni ni-bullet-list-67 text-red"></i> Records
                        </a>
                    </li>
                {% else %}
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'data:statistics'%}">
                        <i class="ni ni-chart-pie-35 text-red"></i> Statistical Data
                    </a>
                </li>
            </ul>
            <!-- Divider -->
            <hr class="my-3">
            <div class="position-relative bottom--8 d-flex flex-column justify-content-center align-items-center pt-4">
                <p class="position-relative text-center mb-0">Powered by</p>
                <br>
                <img src="{% static 'assets/img/brand/blue.png' %}" class="navbar-brand-img mt-0 pt-0" alt="Brand logo">
            </div>
        </div>
    </div>
</nav>